<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:**Xareny González López

**Fecha:** 16 de septiembre del 2021.

**Expediente** : if720811
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: 

# Tarea 2-a)

## Enunciado de tarea 
> Usando compresión de listas o funciones map(sino recuerda como funciona observar el siguiente enlace https://www.pythonforbeginners.com/lists/list-comprehensions-in-python/), resolver los siguientes ejercicios:

>1. Resolver la siguiente ecuación recursiva usando funciones como se vió en clase
$$ D_{n}=(n-1) D_{n-1}+(n-1) D_{n-2} \quad n\ge 3$$
con $D_1=0$ y $D_2 = 1$

In [3]:
# Paqueterias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
# Código de solución estudiante 1: 


[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

In [11]:
# Código de solución estudiante 2


[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

>2. Count the number of spaces in the following string `variable =  relaciónn  requiere,  para obtener  el  valor  de un  cierto  término,  el conocimiento de los dos anteriores`.

In [21]:
# Código de solución estudiante 1: 


[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

In [7]:
# Código de solución estudiante 2


[(1, 688.3299999999999),
 (2, 504.46000000000004),
 (3, 374.79999999999995),
 (4, 502.57)]

>3. Remove all of the vowels in a string [make a list of the non-vowels].

In [13]:
# Código de solución estudiante 1: 


No. orden  Costo total
0     34587       163.80
1     98762       284.00
2     77226       108.85
3     88112        84.97

In [16]:
# Código de solución estudiante 1: 


No. pedido  Costo total
0           1       688.33
1           2       504.46
2           3       374.80
3           4       502.57

In [14]:
# Código de solución estudiante 2
# Para Ejercicio 1


Num_orden   Total
n1        1.0  688.33
n2        2.0  504.46
n3        3.0  374.80
n4        4.0  502.57

>4. Find all of the words in a string that are less than 4 letters.

In [7]:
# Código de solución estudiante 1: 


['notion', 'lambda', 'function', 'origin', 'computer', 'science']

In [36]:
# Código de solución estudiante 2


['notion', 'lambda', 'function', 'origin', 'computer', 'science']

>5. Use a dictionary comprehension to count the length of each word in a sentence.

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


In [9]:
# Código de solución estudiante 1: 


[35.97387961379455,
 63.211195349983264,
 73.90387696517755,
 36.982512376595906,
 68.75395211338406,
 45.86132066984196,
 36.58307493022292,
 56.322083650154724,
 33.9621930206693,
 45.29071317816652,
 74.86289938282341,
 66.51091382521807,
 46.831316244170544,
 44.55796498523391]

In [37]:
# Código de solución estudiante 2


Numeros pares de la lista: [35.97387961379455, 63.211195349983264, 73.90387696517755, 36.982512376595906, 68.75395211338406, 45.86132066984196, 36.58307493022292, 56.322083650154724, 33.9621930206693, 45.29071317816652, 74.86289938282341, 66.51091382521807, 46.831316244170544, 44.55796498523391]


>6. Use a nested list comprehension to find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9).

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [11]:
# Código de solución estudiante 1: 


array([0, 2])

In [38]:
# Código de solución estudiante 2


array([0, 2])